Ext.define('GSmartApp.model.pcontract.PContractPOLine_Confirm', {
    extend: 'Ext.data.Model',
	fields: [
		{name: 'id', type: 'int'},
		{name: 'orgrootid_link',  type: 'int'},
        {name: 'orgrootid_link',  type: 'int'},
		{name: 'pcontractid_link',   type: 'int'},
        {name: 'code',   type: 'string'},
        {name: 'contractcode', type: 'string'},
        {name: 'po_buyer',   type: 'string'},
        {name: 'po_vendor',   type: 'string'},
        {name: 'productid_link',   type: 'int'},
        {name: 'po_quantity',   type: 'int'},
        {name: 'unitid_link',   type: 'int'},
        {name: 'shipdate', type: 'date', dateFormat: 'c'},
        {name: 'matdate',   type: 'date', dateFormat: 'c'},
        {name: 'actual_quantity',   type: 'float'},
        {name: 'actual_shipdate',   type: 'date', dateFormat: 'c'},
        {name: 'buyerName',   type: 'string'},
        {name: 'productbuyercode',   type: 'string'},
        {name: 'dc',   type: 'string'},
        {name: 'product_poparent',   type: 'int'},
        {name: 'parentpoid_link',   type: 'int'},
        {name: 'phuongThucDongGoi',   type: 'string'},
        {name: 'shipmodeid_link',   type: 'int'},
        {name: 'productiondate',   type: 'date', dateFormat: 'c'},
        {name: 'shipdate',   type: 'date', dateFormat: 'c'},
    ]
});